import { describe, expect, it } from 'bun:test';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * First manifest-content test (issue #388): the Android TV launcher contract is
 * pure XML that no compiler checks — a lost `LEANBACK_LAUNCHER` category or
 * banner reference would ship silently and only surface as "the app vanished
 * from the TV home screen".
 */
const ANDROID_APP = join(import.meta.dir, '..', 'android', 'app', 'src', 'main');
const manifest = readFileSync(join(ANDROID_APP, 'AndroidManifest.xml'), 'utf8');

describe('AndroidManifest.xml — Android TV launcher contract', () => {
  it('declares LEANBACK_LAUNCHER in the same MAIN intent-filter as LAUNCHER', () => {
    const filters = manifest.match(/<intent-filter>[\s\S]*?<\/intent-filter>/g) ?? [];
    const mainFilter = filters.find((f) => f.includes('android.intent.action.MAIN'));
    expect(mainFilter).toBeDefined();
    expect(mainFilter).toContain('android.intent.category.LEANBACK_LAUNCHER');
    // Phone regression guard: the phone launcher category must survive.
    expect(mainFilter).toContain('android.intent.category.LAUNCHER');
  });

  it('declares the leanback software feature as optional (phones stay installable)', () => {
    expect(manifest).toMatch(
      /<uses-feature\s+android:name="android\.software\.leanback"\s+android:required="false"\s*\/>/,
    );
  });

  it('keeps the touchscreen feature optional (TV boxes have none)', () => {
    expect(manifest).toMatch(
      /<uses-feature\s+android:name="android\.hardware\.touchscreen"\s+android:required="false"\s*\/>/,
    );
  });

  it('points the application at the TV banner drawable', () => {
    expect(manifest).toMatch(/<application[\s\S]*?android:banner="@drawable\/banner"[\s\S]*?>/);
  });
});

describe('TV banner asset', () => {
  const bannerPath = join(ANDROID_APP, 'res', 'drawable-xhdpi', 'banner.png');

  it('exists where the manifest points (committed, generated by icons:source)', () => {
    expect(existsSync(bannerPath)).toBe(true);
  });

  it('is a real PNG (magic bytes)', () => {
    const header = readFileSync(bannerPath).subarray(0, 8);
    expect([...header]).toEqual([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  });
});
