/**
 * Turns a `CHANGELOG.md` release section into the per-version changelog file
 * F-Droid shows (`fastlane/.../changelogs/<versionCode>.txt`).
 *
 * The source is generated by commit-and-tag-version, so it is dense with
 * markdown a store listing has no use for: every entry carries a PR link, a
 * commit link and often a "closes"/"references" tail, all as inline markdown.
 * Rendered raw in a store client that shows plain text, a two-line release note
 * becomes several hundred characters of URLs.
 */

/** F-Droid truncates the displayed changelog; keep entries inside it ourselves
 * so the cut lands between entries instead of mid-URL. In UTF-8 **bytes**, the
 * unit `check:fdroid` and F-Droid measure — not JS string length: the `•`
 * every entry starts with is one UTF-16 unit but three bytes, so a note of many
 * short entries used to pass here at 477 characters and fail the gate at 517
 * bytes, on the `chore(release)` commit, after the tag was already cut. */
export const FDROID_CHANGELOG_LIMIT = 500;

const encoder = new TextEncoder();

/** UTF-8 byte length — the measure every limit in this module is in. */
export function utf8Bytes(text: string): number {
  return encoder.encode(text).length;
}

/** The longest prefix of `text` within `maxBytes`, never splitting a code point. */
function truncateToBytes(text: string, maxBytes: number): string {
  let out = '';
  let used = 0;
  for (const ch of text) {
    const size = utf8Bytes(ch);
    if (used + size > maxBytes) break;
    out += ch;
    used += size;
  }
  return out;
}

/**
 * The body of `## [<version>]`'s section, up to the next version heading.
 * Empty string when the version has no section (a release whose commits were
 * all `chore`/`docs` produces none).
 *
 * Matches the heading by exact version in brackets rather than by `startsWith`:
 * `0.6.5` must not match `## [0.6.56]`.
 */
export function changelogSection(markdown: string, version: string): string {
  const lines = markdown.split('\n');
  const heading = `## [${version}]`;
  const start = lines.findIndex((l) => l.startsWith(heading));
  if (start === -1) return '';
  const rest = lines.slice(start + 1);
  const end = rest.findIndex((l) => l.startsWith('## ['));
  return (end === -1 ? rest : rest.slice(0, end)).join('\n').trim();
}

/** `[text](url)` -> `text`, applied repeatedly for nested/multiple links. */
function unlink(text: string): string {
  return text.replace(/\[([^\]]*)\]\([^)]*\)/g, '$1');
}

/**
 * One changelog bullet as plain text, or null when the line is not an entry.
 *
 * Drops the commit-hash reference and the `closes`/`references` tail — an issue
 * number means nothing to someone reading a store listing — but keeps the PR
 * number, which is the one link a curious reader can actually follow.
 */
export function formatEntry(line: string): string | null {
  const m = /^\s*[*-]\s+(.*)$/.exec(line);
  if (!m) return null;
  let text = unlink(m[1]);
  // `, closes #1174` / `, references #1168 #1170` — everything from the tail on.
  text = text.replace(/,?\s*(closes|references|refs)\s+#.*$/i, '');
  // The commit ref is a bare 7-hex `(abc1234)`; the PR ref is `(#1173)`.
  text = text.replace(/\s*\(\b[0-9a-f]{7,40}\b\)/g, '');
  // `**scope:**` -> `scope:`
  text = text.replace(/\*\*(.+?)\*\*/g, '$1');
  text = text.replace(/\s+/g, ' ').trim();
  return text.length > 0 ? `• ${text}` : null;
}

/**
 * The section rendered as plain text within {@link FDROID_CHANGELOG_LIMIT}.
 *
 * Truncation drops whole entries rather than cutting mid-sentence, and says so
 * — a changelog that stops mid-word reads like a bug in the store client.
 * `### Bug Fixes`-style group headings are dropped: with the entries reduced to
 * one line each, a heading per group costs more than it explains.
 */
export function toFdroidChangelog(section: string, limit = FDROID_CHANGELOG_LIMIT): string {
  const entries: string[] = [];
  for (const line of section.split('\n')) {
    const entry = formatEntry(line);
    if (entry !== null) entries.push(entry);
  }
  if (entries.length === 0) return '';

  const kept: string[] = [];
  let used = 0;
  for (const entry of entries) {
    const cost = (kept.length === 0 ? 0 : 1) + utf8Bytes(entry);
    if (used + cost > limit) break;
    kept.push(entry);
    used += cost;
  }

  // Nothing fits: one hard-truncated entry beats an empty changelog.
  if (kept.length === 0) {
    const ellipsis = '…';
    return truncateToBytes(entries[0], limit - utf8Bytes(ellipsis)).trimEnd() + ellipsis;
  }

  if (kept.length === entries.length) return kept.join('\n');

  // Making room for the note can itself drop an entry, so the count has to be
  // recomputed from what survives — not read once before the loop.
  const note = () => `…and ${entries.length - kept.length} more`;
  while (kept.length > 1 && used + 1 + utf8Bytes(note()) > limit) {
    used -= utf8Bytes(kept.pop()!) + 1;
  }
  return [...kept, note()].join('\n');
}
